
platform :ios, '11.0'

use_frameworks!

target 'MustacheFoundation_Example' do
  pod 'MustacheFoundation', :path => '../'

  target 'MustacheFoundation_Tests' do
    inherit! :search_paths

    
  end
end
